# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stax < Formula
  desc "Your codebase's knowledge brain — project graph CLI + MCP server"
  homepage "https://stax.glassa.ai"
  version "2.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/glassa-work/stax-cli/releases/download/v2.7.0/stax-darwin-amd64.tar.gz"
      sha256 "7addc85bf198fb64dee323c486dc875668535c7c650db8bc5c3b7e817d84d7a6"

      define_method(:install) do
        bin.install "stax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/glassa-work/stax-cli/releases/download/v2.7.0/stax-darwin-arm64.tar.gz"
      sha256 "6ff87838f18885726141bb8006060ff8f87ea42077ec16c69b75bba8f00cfe3c"

      define_method(:install) do
        bin.install "stax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/glassa-work/stax-cli/releases/download/v2.7.0/stax-linux-amd64.tar.gz"
      sha256 "971d8938216c215213d4eecc026a37794b16bd736ce2af3a850314abd93e2007"
      define_method(:install) do
        bin.install "stax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/glassa-work/stax-cli/releases/download/v2.7.0/stax-linux-arm64.tar.gz"
      sha256 "845f13845155e3003c57c963528a29620db5262630ec7af5703afa86cb8d0d70"
      define_method(:install) do
        bin.install "stax"
      end
    end
  end

  test do
    system "#{bin}/stax", "--version"
  end
end
